# Generated by Django 5.2.15 on 2026-07-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com', null=True)),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com', null=True)),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com', null=True)),
                ('batch_size', models.CharField(default='20', max_length=50)),
            ],
        ),
    ]
