# Generated by Django 5.2.15 on 2026-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='image_url',
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branches/'),
        ),
    ]
