# Generated by Django 5.2.15 on 2026-07-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_branch_image_url_branch_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='batch_size',
        ),
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.URLField(blank=True, help_text='Paste an Imgur or external image link here', max_length=500, null=True),
        ),
    ]
