# Generated by Django 5.2.15 on 2026-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sitesetting_batch_size_alter_branch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Paste exact Google Maps URL here', max_length=500, null=True),
        ),
    ]
