# Generated by Django 5.2.15 on 2026-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_branch_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.CharField(blank=True, help_text='Paste an Imgur or external image link here', max_length=500, null=True),
        ),
    ]
